NFC: Fix compilation error vienna compilation with 16 components
error: vendor/nxp/opensource/commonsys/packages/apps/Nfc/Android.bp:133:1:
module "nqnfc-sources": depends on //packages/modules/Nfc/NfcNci:statslog-Nfc-java-gen which is not visible to this module

Change-Id: I7ac380484263f616389c45dc5a4b8d6d1a5d1896